### ISSUE TITLE
Error: `rcsdk.platform(...).authUrl is not a function`

### ISSUE THREAD

**Issue by grokify** [ringcentral-tutorials/oauth-js-demo#1]
From the community:

https://devcommunity.ringcentral.com/ringcentraldev/topics/getting-rcsdk-platform-authurl-is-not-a-function

Trying to use the tuorial in the URL [https://ringcentral-tutorials.github.io/oauth-js-demo/?distinctId=16197bcf10a97-0973e5a0d1373-a35346...](https://ringcentral-tutorials.github.io/oauth-js-demo/?distinctId=16197bcf10a97-0973e5a0d1373-a35346f-100200-16197bcf10be5#4) which has the

```javascript
  rcsdk.platform().authUrl({
    redirectUri: this.config['RC_APP_REDIRECT_URL']
  })
```

code in index.html. So when I try to get the access token I get `rcsdk.platform(...).authUrl is not a function`

**Comment by grokify** [comment]
Community response:

Hi, Angad. It seems the demo code is outdated. Please try `rcsdk.platform(...). loginUrl`  https://github.com/ringcentral/ringcentral-js#login

**Comment by embbnux** [comment]
The version of RC SDK in this demo is 2.0.6. It is outdated. We need to update this demo with SDK > 3.0.0.

**Comment by grokify** [comment]
Demo has been updated to use JS SDK v3.x and tested with v3.2.0.
